---
    - name: Install Samba
      package:
        name: samba
        state: present

    - name: Start and enable Samba
      ufw:
        rule: allow
        port: "137,138,139,445"
        proto: tcp

    - name: Copy admin_manual file
      copy:
        src: admin_manual
        dest: /usr/local/bin/
      tags:
        - file_servers
    
