---
- hosts: all
  become: true
  tasks:

  - name: install Apache and PHP for Ubuntu Servers
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Install and start Apache and PHP for OracleLinux servers
    dnf:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "OracleLinux"

  - name: start httpd 
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "OracleLinux"

  - name: Update ServerAdmin in Apache config
    lineinfile:
      path: /etc/apache2/apache2.conf # Adjust for your OS
      regexp: '^ServerAdmin'
      line: 'ServerAdmin martin.mato@ingrydacademy.com'
    tags:
      - web_server_setup

  - name: Configure firewall for HTTP and HTTPS
    ufw:
      state: enabled
      tags:
        - web_server_setup
