---
- hosts: web_servers
  become: true
  tasks:

  - name: Add ssh key for user admin
    tags: always
    authorized_key:
      user: admin
      key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHLbfaXRUqSOibSmlXp00TLTefA4I2dBkEM0On7LhPPl ansible 

- hosts: web_servers
  become: true
  tasks:

  - name: install Apache and PHP for Ubuntu Servers
    tags: apache,apache2,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Install and start Apache and PHP for OracleLinux servers
    dnf:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "OracleLinux"

  - name: start httpd 
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "OracleLinux"

  - name: Update ServerAdmin in Apache config
    lineinfile:
      path: /etc/apache2/apache2.conf # Adjust for your OS
      regexp: '^ServerAdmin'
      line: 'ServerAdmin martin.mato@ingrydacademy.com'
    tags: webservers


  - name: Configure firewall for HTTP and HTTPS
    tags: webservers
    ufw:
      state: enabled

