---

  - name: install Apache and PHP for Ubuntu Servers
    tags: apache,apache2,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Install and start Apache and PHP for OracleLinux servers
    dnf:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "OracleLinux"

  - name: start httpd 
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "OracleLinux"

  - name: Update ServerAdmin in Apache config
    tags: email_update,apache,web_servers
    lineinfile:
      path: /etc/apache2/apache2.conf # Adjust for your OS
      regexp: '^ServerAdmin'
      line: 'ServerAdmin martin.mato@ingrydacademy.com'
  
  - name: restart apache
    service:
      name: apache2
      state: restarted
    when: ansible_distribution == "Ubbuntu" and apache.changed

  - name: configure firewall for webserver
    tags: allow_apache,webservers
    ufw:
      state: enabled
      rule: allow
      name: "{{ item }}"
    with_items:
       - "Apache Full"
       - "OpenSSH"
    register: ufw

  - name: Enable Firewall
    service:
      name: ufw
      state: restarted
      enabled: yes  

  

